server:
  port: 8004
spring:
  application:
    name: auth-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/zk_config?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: Lsh123456!

hazelcast:
  address: 192.168.153.131:5701
zookeeper:
  address: 192.168.153.128:2181,192.168.153.129:2181,192.168.153.130:2181
#  address: 192.168.153.131:2181
  sessionTimeOut: 60000
  connectionTimeoutMs: 15000
  sleepMsBetweenRetry: 1000
  maxRetries: 3