server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000 #必须以毫秒为单位指定
        response-timeout: 5s  #必须指定为 java.time.Duration
      globalcors: # 跨域配置
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: queryuri
          uri: https://www.qq.com/
          predicates:
            - Query=uri,qq
          metadata: # 配置每条路由超时
            response-timeout: 200 # 必须以毫秒为单位指定。
            connect-timeout: 200  # 必须以毫秒为单位指定。

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:7900/eureka


