server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: queryuri
          uri: https://www.qq.com/
          predicates:
            - Query=userId,.*,businessCode,.*
          filters:
            - StripPrefix=1
auth-service:
  authorizeUrl: http://localhost:8004/auth



eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:7900/eureka


